name: Update Latest Release

on:
  schedule:
    - cron: '15,45 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Waline Server
        run: |
          curl -sSL https://codeload.github.com/walinejs/waline/zip/refs/heads/main -o waline.zip
          unzip -o waline.zip
          mv waline-main/example/* .
      - name: Commit Changes
        uses: github-actions-x/commit@v2.9
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          push-branch: 'master'
          commit-message: "Update Latest Release"
          files: |
            index.cjs
            package.json
            vercel.json
          rebase: 'true'
          name: GitHub Action
          email: action@github.com
